---
format: 
  html:
    code-fold: false
    echo: false
    embed-resources: true
    published-title: "Fecha de actualización:"
    author-title: "Autor:"
    toc: true # Habilita la tabla de contenidos
    toc-title: "Índice de Contenidos"
    toc-depth: 3 # Nivel de profundidad del índice (hasta h3)
    toc-location: left
editor: visual
execute:
  warning: false
  message: false
footnotes-hover: true # muestra notas al pie
smooth-scroll: true # suaviza el scroll
code-copy: false
include-in-header: HTML/header4.html
css: CSS/style.css
---

```{r,echo=FALSE}
source("source.R")
```

# Personas gestantes y puérperas

# Niñx

Control de niño sano

Dx prevalencia/incidencia

# Mortalidad

::: panel-tabset
## Mortalidad materna

## Mortalidad infantil
:::

## 

# Redes profesionales

:::: panel-tabset
## Total provincial por regiones

```{r, echo=FALSE}

grafico_profesiones_regiones

```

## Distribución por Regiones

::: panel-tabset
## Región Confluencia y HPN

```{r, echo=FALSE}
tabla_confluencia
```

## Región de la Comarca y del Limay

```{r, echo=FALSE}
tabla_comarca_limay

```

## Región del Pehuén

```{r, echo=FALSE}
tabla_pehuen
```

## Región Lagos del Sur

```{r, echo=FALSE}
tabla_lagos
```

## Región Vaca Muerta

```{r,echo=FALSE}
tabla_vaca_muerta
```

## Región Alto Neuquén

```{r, echo=FALSE}
tabla_alto_nqn

```
:::
::::
